### ISSUE TITLE
説明の記述順

### ISSUE THREAD

**Issue by tosseto** [sekilab/rule_slack#5]
* その他　を　共通項目　に変名
* 運用ルール
* チャンネル命名規則

の順番にしてはどうでしょうか？削除は「アーカイブ」で不用意な操作を防ぐため基本的には管理者以上でいいかなと思いました。

**Comment by hiroyamaeda** [comment]
ありがとうございます！以下にしてみました！
べっと、削除は管理者以上ということに設定変更しておきます。
- 共有チャンネル（デフォルトチャンネル）
- 個別チャンネル命名規則
- 運用ルール
